name: main-build

#this drops to nuget

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build Comet-Nuget
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: git submodules command again
        run : git submodule update --init --recursive

      # - name: Setup .NET Core
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.x

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '[16.9,16.10)'

      - name: Install and Run maui-check Tool
        shell: pwsh
        run: |
          dotnet tool install -g Redth.Net.Maui.Check
          maui-check --ci --fix --non-interactive --verbose --skip openjdk

      - name: Restore Comet.sln
        run: nuget restore Comet.sln

      - name: dotnet Restore Comet-Nuget.sln
        run: nuget restore build/Comet-Nuget.sln

      - name: dotnet Restore Comet-net6-Nuget.sln
        run: nuget restore build/Comet-net6-Nuget.sln

      - name: Build Comet-Nuget.sln
        run: msbuild build/Comet-Nuget.sln
 
      - name: Build Comet-net6-Nuget.sln
        run: dotnet build build/Comet-net6-Nuget.sln
